version: "3.8"

services:
  nginx:
    container_name: em-server
    build:
      context: .docker
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./app:/var/www/html
      - .docker/nginx/conf.d/default.conf:/etc/nginx/sites-available/default.conf
      - .docker/nginx/conf.d/default.conf:/etc/nginx/sites-enabled/default.conf
      - .docker/nginx/logs/error.log:/var/log/nginx/error.log
      - .docker/nginx/logs/access.log:/var/log/nginx/access.log


  php:
    container_name: php-fpm
    build:
      context: .docker
      dockerfile: ./php/Dockerfile
    networks:
      - internal
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
      - .docker/php/logs/php.log:/var/log/fpm-php.www.log
      - ./app/composer.json:/var/www/html/composer.json
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    container_name: em-db
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - events-data:/var/lib/mysql
      - ./app/migrations/init.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: events
      MYSQL_USER: alex
      MYSQL_PASSWORD: alexsecret
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      internal:

  redis:
    container_name: em-cache
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
    - events-data:/data
    networks:
    - internal


networks:
  internal:
    driver: bridge

volumes:
  events-data: